# Learn Numpy

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this:

NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences.

NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [1]:
import numpy as np


In [2]:
# create numpy array
my_arr = np.arange(1000000)

In [3]:
# create python list
my_list = list(range(1000000))

In [4]:
# compare performance of numpy array vs python's list
%time
for _ in range(10):
    my_arr2 = my_arr *2

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 10 µs


In [5]:
%time
for _ in range(10):
    my_list2 = [ x * 2 for x in my_list ]

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 8.82 µs


In [7]:
# create random array
data = np.random.randn(2,3)
data

array([[-0.23707837, -0.03738394, -1.27066896],
       [ 0.66379768, -0.52115164,  0.05398351]])

In [8]:
# perform operation on all elements of array
data * 2

array([[-0.47415673, -0.07476787, -2.54133792],
       [ 1.32759537, -1.04230329,  0.10796703]])

In [9]:
data + 2

array([[1.76292163, 1.96261606, 0.72933104],
       [2.66379768, 1.47884836, 2.05398351]])

In [10]:
type(data)

numpy.ndarray

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [19]:
# create ndarray from list
lt = [1,2,3.5,4,5,6]
data = np.array(lt)
data.shape

(6,)

In [20]:
data

array([1. , 2. , 3.5, 4. , 5. , 6. ])

In [21]:
# nested lists create multi dimensional array
data = np.array([[0,2,4], [1,3,5]])
data

array([[0, 2, 4],
       [1, 3, 5]])

In [22]:
data.shape

(2, 3)