# NumPy
Numerical Python

NumPy internally stores data in a contiguous block of memory,      independent of other built-in Python objects. NumPy’s library of      algorithms written in the C language can operate on this memory without      any type checking or other overhead. NumPy arrays also use much less      memory than built-in Python sequences.

In [1]:
# NumPy arrays are much efficient than python lists

import numpy as np
np_array = np.arange(1000000)
py_list = list(range(1000000))

%time 
for _ in range(10):
    np_array2 = np_array * 2
    
%time
for _ in range(10):
    py_list2 = [ x * 2 for x in py_list]

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 4.77 µs
CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.05 µs


In [2]:
data = np.random.randn(2,3)
data

array([[-0.08692989,  1.01676893, -0.53734647],
       [ 1.05832862,  0.51515025, -2.36178093]])

In [3]:
data * 10

array([[ -0.86929891,  10.16768928,  -5.37346469],
       [ 10.58328618,   5.15150252, -23.61780928]])

In [4]:
data + data

array([[-0.17385978,  2.03353786, -1.07469294],
       [ 2.11665724,  1.0303005 , -4.72356186]])

In [5]:
data.dtype

dtype('float64')

In [6]:
data.shape

(2, 3)

In [7]:
# creating N dimensional (nd) array
data = [4,5,6.6, 7.7,8.8]
arr = np.array(data)
arr

array([4. , 5. , 6.6, 7.7, 8.8])

In [8]:
data = [[4,5,6.6, 7.7,8.8], [2.3, 2,4,6,4.4]]
arr = np.array(data)
arr

array([[4. , 5. , 6.6, 7.7, 8.8],
       [2.3, 2. , 4. , 6. , 4.4]])

In [9]:
arr.ndim

2

In [10]:
arr.shape

(2, 5)

In [11]:
arr.dtype

dtype('float64')

In [12]:
# create array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# create array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# specifying the type of data
arr = np.array([1,2,3], dtype=np.float64)
arr.dtype

dtype('float64')

In [20]:
arr = np.array([1,2,3], dtype=np.int32)
arr.dtype

dtype('int32')

In [21]:
# type casting
arr.astype(np.float64)

array([1., 2., 3.])

In [22]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
arr2 = np.array([[0, 4, 1], [7,2,12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [28]:
arr3 = np.array([[1,2], [3,4]])
arr3

array([[1, 2],
       [3, 4]])

In [29]:
arr - arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5:8] # its a view on original memory block

array([6, 7, 8])

In [32]:
arr[5:8] = [12,12,12]
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9])

In [33]:
arr[:]

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9])

In [34]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d[0,2]

3

In [38]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [43]:
data = np.random.randn(7,4)
data

array([[-1.15118378e+00, -2.25083186e+00,  7.10361496e-01,
         3.52477377e-02],
       [ 2.92621369e-01, -1.43029803e-03,  5.32816202e-01,
         8.70299821e-01],
       [-8.17982348e-01,  8.86319325e-01, -1.30886166e+00,
        -1.05045001e+00],
       [-7.27739466e-01, -9.25259347e-01, -1.47338977e-02,
        -1.50273347e+00],
       [ 1.45044921e+00,  1.03857729e+00, -3.86959534e-01,
        -1.88506938e-01],
       [ 3.99348625e-02,  4.32739721e-01,  1.57900931e-01,
         2.36262096e-01],
       [ 1.66641916e+00,  9.75765757e-01,  1.62997124e-01,
        -3.29534286e-01]])

In [44]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.7103615 , 0.03524774],
       [0.29262137, 0.        , 0.5328162 , 0.87029982],
       [0.        , 0.88631932, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.45044921, 1.03857729, 0.        , 0.        ],
       [0.03993486, 0.43273972, 0.15790093, 0.2362621 ],
       [1.66641916, 0.97576576, 0.16299712, 0.        ]])

In [45]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.29262137, 0.        , 0.5328162 , 0.87029982],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.03993486, 0.43273972, 0.15790093, 0.2362621 ],
       [1.66641916, 0.97576576, 0.16299712, 0.        ]])

In [50]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [51]:
# extract specific rows
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [52]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [53]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [54]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [60]:
arr.swapaxes(0,1)

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])